[project]
name = "Flask-Classful"
version = "0.17.0.dev"
description = "Class based views for Flask"
readme = "README.md"
license = { file = "LICENSE.md" }
maintainers = [{ name = "Pallets Community Ecosystem", email = "contact@palletsprojects.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
requires-python = ">=3.8"
dependencies = [
    "flask>=2.0",
]

[dependency-groups]
build = [
    "build>=1.2.2.post1",
]
dev = [
    "tox>=4.25.0",
    "tox-uv>=1.13.1",
]
docs = [
    "furo>=2024.8.6",
    "sphinx>=7.1.2",
]
gha-update = [
    "gha-update>=0.2.0 ; python_full_version > '3.12'",
]
pre-commit = [
    "pre-commit>=3.5.0",
]
tests = [
    "asgiref>=3.8.1",
    "pytest>=8.3.5",
    "webargs>=8.6.0",
]

[project.urls]
Documentation = "https://flask-classful.readthedocs.io"
Source = "https://github.com/pallets-eco/flask-classful/"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "flask_classful"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]

[tool.coverage.run]
branch = true
source = ["flask_classful", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "ISC",  # flake8-implicit-str-concat
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.uv]
default-groups = ["dev", "pre-commit", "tests"]

[tool.gha-update]
tag-only = [
    "slsa-framework/slsa-github-generator",
]
