[tox]
envlist =
    py3.{12,11,10,9,8}
    minimal
    style
    docs
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
dependency_groups = tests
constrain_package_deps = true
use_frozen_constraints = true
commands = pytest -v --tb=short --basetemp={envtmpdir} {posargs}

[testenv:style]
dependency_groups = pre-commit
skip_install = true
commands = pre-commit run --all-files

[testenv:docs]
dependency_groups = docs
commands =
    sphinx-build -M clean docs docs/_build
    sphinx-build -M html docs docs/_build -W

[testenv:update-actions]
labels = update
dependency_groups = gha-update
commands = gha-update

[testenv:update-pre_commit]
labels = update
dependency_groups = pre-commit
skip_install = true
commands = pre-commit autoupdate -j4

[testenv:update-requirements]
labels = update
skip_install = true
commands =
    uv lock {posargs:-U}
