name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.12', '3.11', '3.10', '3.9', '3.8']
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
          cache: pip
          cache-dependency-path: requirements/tests.txt
      - run: pip install tox
      - run: tox run -e py${{ matrix.python }}
  min:
    name: Minimum Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: requirements/tests.txt
      - run: pip install tox
      - run: tox run -e py-min
